apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre-web
  namespace: argocd
  labels:
    notification: "true"
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: calibre-web
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/la7eralus/k8s.git'
      path: apps/calibre-web
      targetRevision: HEAD
  project: default