apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    notification: "true"
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/5olu7ion/k8s.git'
      path: apps/pvs
      targetRevision: HEAD
  project: default