---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: adguard-home
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: adguard-home
      app.kubernetes.io/name: adguard-home
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: adguard-home
        app.kubernetes.io/name: adguard-home
    spec:
      containers:
        - image: adguard/adguardhome:v0.107.43
          name: adguard-home
          command: ["/bin/sh"]
          args: ["/opt/adguardhome/data/startup/startagh.sh"]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 53
              name: dnstcp
              protocol: TCP
            - containerPort: 53
              name: dnsudp
              protocol: UDP              
          volumeMounts:
            - mountPath: /opt/adguardhome/data
              name: data
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 60
            timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: adguard-home
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: dnsudp
      port: 53
      targetPort: dnsudp
      protocol: UDP
    - name: dnstcp
      port: 53
      targetPort: dnstcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.4.10
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/name: adguard-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-static
  volumeName: adguard-home-data