persistence:
  defaultClass: false
  reclaimPolicy: Retain

csi:
  kubeletRootDir: /var/lib/kubelet
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultDataPath: /var/mnt/longhorn
  backupTarget: nfs://192.168.4.33:/volume1/k8s/longhorn/
  allowCollectingLonghornUsageMetrics: false
  defaultDataLocality: best-effort
  defaultReplicaCount: 1
  defaultLonghornStaticStorageClass: longhorn-encrypted
  replicaAutoBalance: least-effort
  storageOverProvisioningPercentage: 200
  storageReservedPercentageForDefaultDisk: 20
  allowRecurringJobWhileVolumeDetached: true