apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    notification: "true"
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-cd
      targetRevision: 5.53.12
      helm:
        valueFiles:
          - $values/apps/argocd/values.yml
    - repoURL: 'https://github.com/5olu7ion/k8s.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/5olu7ion/k8s.git'
      path: apps/argocd/extra
      targetRevision: HEAD
  project: default
