version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: ENC[AES256_GCM,data:VP0+wtw651ugY0/1x3uKeye2UXUxXdk=,iv:R1jjzhgMo/mYFc5lJvFLIgwngRN0kGCaKYXfmUBpAws=,tag:MQPliD79cFjeE1m/M5t7IQ==,type:str]
    ca:
        crt: ENC[AES256_GCM,data:eVHsg9XW+FS8dwltU61aoh5PSkw97d4gHH8saHkvUqyp+jDekXIzN2UM03wEkCuR/5tLaUunRQVbjsPRDy93ETcYj1mQrqT0lW6qK0DYI16vov3vg5YYolyO8apGRUZTwA+2rJQoxgQZq/ter+uMJ2t4oCrY0NJGq66xpvG1Fa96VPnyhY4Xs59SE233kxGpg9RZN4SkBcoDW8wFuHKtA4zmPtKNklxxyY+mwMKWPr9KGnExBxB3TQ04t8kXtSp9yiiI6egJPRBMjOwnFEMqRzXIWXKFYjgsp9BIpc1F56oMHaZYX72B8GtfTz1X9H37IcZut8GmTWkUmLGuOgYdHFTNoNARuC4S1QsvmUj2LuS1pg/rgCZlfWkqAoZv+ZTIrVVa8ADrYwMvpHiO+4bp73KlLPjf1LY6aREGC3rDTmfKQQzquyAwlfbu3ZvW7Sb+1O6r5VSDuhOH6/77Pq4G+ts4pVo7hPBUIzOknLVfD46KGmeelIJiQgYB7kwVZHq0wS4c2sXcbFib2G6/b0NYf2DwBBOrAU8texg8XgNqWUqPdwB7WkFIMqQ6j9WeYZIZOPlEC+WPj5YKH6mk4XrXQ0fLgermRgHvXUKAsy2FMAvysuFwJpGyBNCGYXiaMed8XDUxm1KT6gC1d0KgSlG7VpTlLw0QOH2coQHY6gmyWI+tNTxjp/ajFyEXC/hQ452hAcEuofmF88JpIN6/oUZbQPabT+458lJkVe60VYr+o5NkXkNjKm3RpuY0Ljz4StABWDMFMnGDLt/b+bCmxdV0aTEJ64EaLFG8orJBL1mylRUXR6+icaffuD2rYsIF7lpz4bKFPT7ymzwbetdMCJUjxcghIQhr8tF3X5nR3bvufMrP7rGs,iv:JcXKqaPYQ3WPhpqDahU2tCWziZxveqMvEDKQSxD9XWQ=,tag:4iC4vSJypfCyBr7MfUV1hQ==,type:str]
        key: ENC[AES256_GCM,data:ZaIaCuIus36eatmE/Fr7UR1sQeDvVJnCbg+/vjJ8jkM0DwVYh7wGUeeGFvw8c56ev+a7YmTg9vvNDwKP84gu7kusGlS5BNqw6h1lxljrIBnuLilucPHMU776VUGt5Ezle+TUA1AeSlZnpEMrlv/XY1xYr2dWK8qzCQLq+KOWnaie03zdk2t2rYKfo5FmMJgYHYgGXn5D5ve9er4USDScYW9rsZ1/iv70pZ3SWLO8o7JnVQMQ,iv:aJ/8Qu/wkeY90EwczYpnaK0Vh1/VSG6qsiKgK8LSEU0=,tag:YHiCAPbF9Qo/FSMoREx7Ew==,type:str]
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.29.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
        extraArgs:
            #for metrics-server
            rotate-server-certificates: true
        nodeIP:
            validSubnets:
                - 192.168.4.0/24
        extraMounts:
            - destination: /var/mnt/longhorn
              type: bind
              source: /var/mnt/longhorn
              options:
                - rbind
                - rshared
                - rw
    systemDiskEncryption:
        ephemeral:
            provider: luks2
            keys:
                - slot: 0
                  tpm: {}
        state:
            provider: luks2
            keys:
                - slot: 0
                  tpm: {}
    network:
        hostname: talos-controlplane
        interfaces:
            - deviceSelector:
                busPath: 0*
              dhcp: true
              vip:
                ip: 192.168.4.5
        nameservers:
            - 1.1.1.1
            - 8.8.8.8
    install:
        disk: /dev/sda
        #siderolabs/iscsi-tools, siderolabs/qemu-guest-agent, siderolabs/tailscale, siderolabs/util-linux-tools
        #iso: https://factory.talos.dev/image/077514df2c1b6436460bc60faabc976687b16193b8a1290fda4366c69024fec2/v1.7.1/metal-amd64-secureboot.iso
        image: factory.talos.dev/installer-secureboot/077514df2c1b6436460bc60faabc976687b16193b8a1290fda4366c69024fec2:v1.7.1
        wipe: true
        diskSelector:
            busPath: /pci0000:00/0000:00:05.0/0000:01:01.0/*
    disks:
        - device: /dev/sdb
          partitions:
            - mountpoint: /var/mnt/longhorn
    registries: {}
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
    time:
        servers:
            - 192.168.4.1
cluster:
    id: ENC[AES256_GCM,data:579gtMBwHjM744pYjaaGTLHPKL7JdRkc0u2QNACFsdFahGhjUc1Rr9Nf4eE=,iv:zhoWgf8wKVmGRGR4cpMsAtVMG1XY+ZiFX45NIgfAZvs=,tag:I4qfgK00ytBJOsoDOh2IQg==,type:str]
    secret: ENC[AES256_GCM,data:kK+nQLvZDAoOUUYmcf3Jv5ksQwoi9s95X74WL+rXbLhqxU4bZQlfnRzv7O0=,iv:8BBU7+h46UvzynkPVp50TauaFHnYIl0DYE1yIHNJhkc=,tag:u2US8ZMbEna2XzEVpDMQ0g==,type:str]
    controlPlane:
        endpoint: https://talos.s3rv.dev:6443
    clusterName: talos-proxmox
    network:
        dnsDomain: talos.s3rv.dev
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: ENC[AES256_GCM,data:KzID1hVIzQvYD+pRnNP40CSLFZQQsYs=,iv:GWfU11CeI38vT3VV7DZvlRhylF9cq8EEfMAB0X8mogw=,tag:F6eBAzx9k4TJpdvDw2G7iA==,type:str]
    secretboxEncryptionSecret: ENC[AES256_GCM,data:14xD/HpKba0z5n8bL9grq8Lyg9MYH2E1uah3od0tPX8QmtVzBrUNJWc34fw=,iv:6KYk5vMXpK4oekSjX40RudZ2yxOICJ5YyNQ4LKkKE+k=,tag:Oy4P8FeTOAJyY6kY2KkABA==,type:str]
    ca:
        crt: ENC[AES256_GCM,data:u5fxFxjzPodBh9dRcSea3yj0E/zRDxfhCrV5SLyuOOJhgXLJcujrthjeVR+z4XN5BFeZXBj3+yUB0q7LRyJ0SciFyyjngYpT6MlPhIOLRxoVWFvAidhqHVogVu5K8++xmlgh9240O5JOq18ZUYIfAcvprGn8IuvGY9s57ieInSv25t+OmA/Sx9EBDTk0ml1v8Os5BidaxBDyu4L0d87oo6GJbDqvKjYXSbwHAeYZjv3jsiGYaIbUh+hrWCHjyW2iDLIbsg+Ns0bNHfKI+yfqYIY60K+je2MULI8wTCPQk1+UtTSltm4bLCuIfY2DE3E724fjqlUp36+XFar2BqOuwD6b30DOICEWvI26kKASTA7AqyuDk7ggQeCZDI/Q6YtDmeI8zoAoDE4ixsi0/2xHkBfYp4lZmsthqy0EVYeJoD4g7cd//kiphfEf83oY9cZjZCPicmyOtM2TQBxhkaEgRAhSo/XQEG46qBpNoqJ1WXs7O10vA6gnkPb4anNnXrp1SiiAUPqWIoFp5gT/Ie1e7BsB0aGggTS10pNqEGmuGw+LRmp6iMuTP1Q9ffC9n7U4uKpbwrpVwDPXN7XMacc70NStNWP2xL3XYj/FFg7xiA6I+ppuHSLbTWyB3eCTax4j1O/6lmle0yJVb9EryNsdj7Edz1n9SMfG/un8b5n50RRufPOa3Ugv6ofuowkUiWIXMMbsF2qluPQJTyD9Cf8KlSJRSI+N7qfUMWicxf+oObcG41KNGbJYnjCtDjy+QirS43rWiqgNRAofAdNxXGOdH1xbFcv1HbdopI7R4EMSN6ppVQWQ/xqyP3HKug+6GhuMhVBchTXZ7IMuqO5s4KYWmjCy2sV12UZjgkPxQTzyNnBIfTeO8tXd+RYB8qH2Ug0UJ0VETOAuYvuAIhGo8OQhAVPFSj0yP1v74keXevjA+PnylCgPVZ7IlmxcW9uFgG3loy44EBWZU7CvTiecAHZrnOj8rfnfcaK1CT69x3kkrdjWQgUH81ICdABbv1Uu01ha2LCwesKJ5osySqF4yYr2dyQafLtB+9gC6USZOA==,iv:hLmek7dJJHLrDO/N22A6T2Cm3xup7NTmyDAoBXqueEk=,tag:C+Hnq1kLAzbRsDi1MPhddg==,type:str]
        key: ENC[AES256_GCM,data:MGZgyqhAoT4y2ym+esvtakkgRcNOiQFf89KtVWXPqb92uqgwL3vJnTJEqvOGuXDqgTnJjS88R22YjXZk5K+nHVNyyFmwWjIjPlX6qRNOGWmIvGUWx2o5WfuuBgLRlppYGeKt8robRtvOKaL+FWWVfOecl7lunIlCboHDpixgpM88Cy4MXLBrKqjLmEb4HA2MkzvxrujHtf2WKvPOXRipmnZji4UzALg2Mj4B2X7mVnHcvZhR6DqM3V3e63TSORe9cNM20KhbJ6BWuNwDMu1noqS7KdVL+dqen0aRSza6wG4h+V4Ba3R3HEsvQcoxFiQVfF8nG0+PjwSzAhKv6XS+axKKqyhDCkifJyna2fvrKtW8RMVTzvTNW47tNQQbD2aWkd6A6CD74/iz2mnWTvZwPA==,iv:6N6OvRf0uErn65Or0f5RyPOHiL/VvD78AxULkB/3ygI=,tag:UWdPAu1kyXMbAkMVG4NL8g==,type:str]
    aggregatorCA:
        crt: ENC[AES256_GCM,data:kcr0zKZka5CmuR9rrLeUYk5T/kkoBq9IqswYR1Iksfz9XVxijypJJf5yhReweEzLAfJQ7r02FmsX9PfYnxXj2VXi2myZFBAzy/1v5/g3krd13y8Xia5P0nPj0lxGBznpSysgLkf6tvXRPVszix1ZCoW4CLmiB5bKbCxzzv173mnXIpx9ZnbuAnSuyQvE8RrgGPTOGvgPcWKHoX/z3yBVd3adECCyjSCmRIJ9C/UBo5hpapf73zOiTs2wQu2x3+9rNVfAwsRQYK53ytNXAkyMRD47z82s5sUSaDXs8GqZqYOqEUwivP58LeSNQbUcs0z/kQY3NlJYzt1Bd6217QuDbffyRfEOiynytBZ5y6rSAKAALJMRhvRaYf4Okl/k7L3/Mpai8F8wFfX4XAWRT5T186w183EXtu4mJNPkP99qMwt4iqiX0Os2Ra/rWn9LIgxMut/q+uIYXL/txb/NYlGXSm0zjIkIolOF0rp68fRFDkSsO+JZa6XsKzZEVKXrWZ1BIBlf0qsBtjpKM2zk+jVmD5vND5fxsrjc3Q56I3a8tgxUIZ+dDT+TWLCQBmTihPhcDBLlAjq3Lfd5xcACxvq69rOZbQkAyXCDo9LvsdB1hEO9KVi6yFb8Mnb1npbd+jDAOa2KR21mOtBSqU9b66BfsBGpzNxBVUCWMramL25v8vp+9XPdixGfqhhLN7fhneR45KIT4Qh6+PiN2ELiwhi2/kdUv+YwuY6/XLtCiyK37HEvUGvD9i4Oj5Wm3mnIG7hjGh/n5U76I9ISErfIhqx5byIrY7rpyS8zh53lULTWdprv34mHYD7QlJ1jKINWVhDZYOz5MKowN0O3R0yZ+f0c0LS6ViVL/p6AzWWkTDht/mWrmTD6WhvqvHZzyugiMYY8dKZGZLgiKJXHcYG0eV0zJCeANM5kLBJSNm8vYDx8Hir0Xiz32GBj7PQm/SUyCyD9,iv:K8DTDvkWcbg4+TtZsqZTgq4zXSntUTlDLKZAdbnIohM=,tag:uj73WpC7Q4jIC/x2vED/jw==,type:str]
        key: ENC[AES256_GCM,data:Vsi4J6YoXlIbqTIzVfqGmvFR/9sOu+KWihLOGGa2ETImdZyGjhMAB7gtogq3rNBjufuvbpaA2Fl4NPai3zZcXt390id69wGMVX2+YgLq3tH74wpjPS+3jRnQEP74ZHsx+I/zRgnvq61IDdVe+3nF2sjv6raREifOrazMt2NZKRahRh8e0vYcaTGCS1wlL9gDscW6uB37+RYZnwuqmeHYM1xyQt0GF4SXF34kS/lkoM2AWNXA26cODD4lgvUNFApYXmR9GmijBaop6042hoXtP4v3UubR+mt7abidMKqID7KciKHg8CpLnZBBbKtVI3wR2IOER0bJGfcjBRAZdUtnxCEXl9DgcomMBpTkrZMMWeZoNwjDPDS7rY9Md3gFUX7PWoz8M1xJNYadIgp3rLHyLQ==,iv:bFChbzFNQr7YIRdd5G9aDh9nMys9xBxvbJrlfQvpsLw=,tag:Iy1K+HDthRI26nctAdRpww==,type:str]
    serviceAccount:
        key: ENC[AES256_GCM,data:w2L7ShV0z6cFPIkC9z2iIV2JoHPFBr8I7Ew11AuDkj7qM1IQhQm8mAXofMA7dB9IQIlVO5XRUcoMflCTMQvM1UFHMEu0lORteigKpbSS8d5V17nnaUlma9SQe6jSafBODLMMs+WBja5wRUc8g5dgAxOCqtzXFqqF/brmFZ2phD86JVy/hR6fAqMt5kx7+l+PHG8Us11WoTc8S+pa6Z1mM/WBeKboXqR6EllX8LyxD3EichfCdB4g7KlQQH4WjBUSkZH10cL3H6C/RwLGiVb8jwUap/OcL0hdVlUTed2d2Z/sagFaQqcZDjCEgTSErpStzIlJi1yAtnax1D2bv0xgp+VQjGTX4MPrwtz2M0KYbd4vJV7rXL6PG1veXMF4WkPERknnF8CN+KCKDZ7nCHUEXQ==,iv:mMvFV4LbhxnjVlhiqbimU516Ft7aVJZo34uYczCfcys=,tag:QuNp2FM9/BmZyCL2yZmquw==,type:str]
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.29.0
        certSANs:
            - 192.168.4.5
            - talos.s3rv.dev
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: baseline
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: baseline
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: None
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.29.0
    proxy:
        image: registry.k8s.io/kube-proxy:v1.29.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.29.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        advertisedSubnets:
            - 192.168.4.0/24
        ca:
            crt: ENC[AES256_GCM,data:6WiGcn9SA63iYdw7B+kZf0hETn1dpXwU2xgURTu3Mx7ZpbkjflWatAkjvgnJxjT7g2LnfZIVmZHA3EwWuFp6OExo+ZpJrrW0SiX/4mBiGry4lowIt7FD2KkpuzDFpyRQC3ogCbgn+MY+MKzLXf+55BPy5Fa4RNGhh+TpebrRW66jJ9xX8tC4wlhNCYr1r/L1MKL2KAWMCgo7uKw3K6QvRsfl618C2O+eeviY4zLO8GWIQVG3uowKR4axGk+UgAoRIN0ZKm205/5ZHgyQIPfAZLPt5SAHsomIxOH0Hm/Nb4PvrQb3CvccJEBky3JZqq8EKxE9uT7a1pCSQhSVlftLxc1Y60slu70OkMinlz65NgJl61lutDh0J+1A2iOctY4jL0/2UWCSuYkyBMdqHJTJjrMi4vBq84+QtXvXY0Yf4aYfZREq4cz3DfLqmggFgUGuCJv5QcA9NiMQZf0r/pUM/Ptbao0JGEDquqkLL8DCwiJb4/k4raZeRdw5Dxrh69SqRS02MN0MHzkP8BcUw16Kop1QOiLIpiyyo6c5itiR8IhjtL2tEU3VyxdyPD8BmyyMT4pqglM77oot0DSp8Wco0db7omZ2VLEl4FnWEBZ3ATe1jWcGPc5YSQoueLNaEUy7ohgNTVghtBQdzfvdO24VMkSG/i31+zOa4J9hYOVbjin22dkHwX/LAMgNMORyqYeCP+zrdy7ken3BVITa9ehBg3SX3dZuIPwtTMTlsEgGETvoDUjZDKXFrshIiN+oqBxvXInmY5L3lx5vzFnc7QyWESc0GrOn8KEg404ETZp/KPDdPNAIYL7HlYcZTzs6qhJxPrdNh4PPJAuM9J1dNDDFZvKJmIC+zYyNYOvbg6djrlanMhKR9F3gcrNz5Q891E8fYwHmlbfqkXODFf4XczOakyOHf3P0TAqxXPykB1cDQRv1uGOSQ1uBG5+73TQuY/VXmVEbGXfMOypzj6KTW0QKRWlXSLncZhY9GAZo1iICyZDS8Xqu+UO2f7BThGhOfF5X8hgxgg==,iv:li6peDFl++h+fkOtgiC7tJRuPZxAsI3JgitTUAyL5Us=,tag:A8goKMaKgGQ/WFiTG/juuw==,type:str]
            key: ENC[AES256_GCM,data:C0nGpTL7LI4Z+c/kKWv4u80SgSOe9w86K4yRLbHzgjZubHPrcHMz7AJ8FyQ/KJZONQ+fK8tH4Bp0zgfVcb+ZwrMO4PJ+ZWU0/8uFzOaA68FUyl1+cje9W4mQavUOUF/id0sD+5D0mmlRxyDuvQhSS6i3I8AnHroOYLWH3+gQERvdG6cq9dN5xkYkkr0uL1gWn18a2KSGlD/Jjn5znsx+iV876qPT5F5Fyd808RC4FesJgl3lI6mO1u3M0Hsatu5o6D9HXUvHJ+mA/8vlVWaca8Aw2Z/TZ+YfGxOGr62tGCkTW1vcpGI0U0OLWNMNZt1PYY+KoWcBiLZW+d53pmcJo1imjYwkeEEttsTmRDUuPqgRvuy/mtvbiL5rcuiFSuzMfXOQvk09xcA9q/5P8hq0Lw==,iv:PftB9QmlrJMfzOH1qBm1OvlvGr6QAZDc2SNpN5XaDME=,tag:lIFB6d7Oy+N7GUJJS/kjFg==,type:str]
    extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    allowSchedulingOnControlPlanes: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xjszg77q3ddquyvgh7scmwh27hk4ns0uef5w4y5feq2nnc0v8y4smgdan7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q09DYm94UkdHVkVMZjg5
            SkRQM2Z2ZllLYWljTlBGZXZtSVlGMGpqcldJCncvL3FQUFZMejRudDNzUlREL3A0
            TGQ3Mksrd3ZrL1pvZDEvaTdKMlNqMjAKLS0tIEZ1OENRclNYMHNRRGY0Unk5enRl
            MERTanpaNnlxcmI1b2w2eUp5TWJYSWcKlJdYwPxRBJXsY0d+/rBgDAXFC8pPBpyN
            +4vu+S54PTYFBNNyOClr5kVONfXQHQ0WWwTgcFV0Z2foR4ULuPC2AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T10:41:07Z"
    mac: ENC[AES256_GCM,data:U4RbNHlCOt2WwQqX9FvUyIcKEQPlzKUNNatNEhkw1Y2CUkbs75fedhjkJzoFrsvT0axJs5CasUZEQn3izHa4AnoV1pNbMCIANJefxYiANDVMzRfEjjPNW4ubgl3eAIa6erb7++2xBPBwVoFscnG0EsmJ7XBi3iwcjC65aam8QV4=,iv:9B+YmNUC/QirziVefGWUfQvqT6seZdaHVQn7uCAOWKc=,tag:/+QIDEMvpm2U+Nq+eZ6ZKA==,type:str]
    pgp: []
    encrypted_regex: ^(content|tls.crt|tls.key|crt|key|secret|secretboxEncryptionSecret|token|id|ca|data|environment)$
    version: 3.8.1
---
#talosctl patch mc -p @ext.yml
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: tailscale
environment:
    - ENC[AES256_GCM,data:upuzGBRM03b9FQw64+PTIIno6c3XuNM6HIdv6oGUpGWOiQ23ATp6s++o49jXEMYwAVbpvlDQxUlUwHg2WSeK+6rd0/H50tRa,iv:W21DCdSkwMScbxQ2VaAMDUJRI/OV9p3GD49DSwr/sUo=,tag:qMRqKKtWDcAStZHB0Yaqeg==,type:str]
    - ENC[AES256_GCM,data:KBKY2V7ip/pz7SLG0fPLnAYoiE9kYJHa,iv:a1zPSu+C/yRbZGTN82BgM8goJs1qqTt0BxqqWE95saM=,tag:FQAZLY9H5Z+rZQjD1mPajw==,type:str]
    - ENC[AES256_GCM,data:ow4g+9rKR+pIWy2UtQ5R8g7CcE3X8GCQHEj7cvAXWa3l/Hc=,iv:6Ko6felN6eEpHr7s/EyfJ1NmRIsgB78zxDBrTE9QXSI=,tag:LZI4kwbb4l6PNEf++xOS9Q==,type:str]
    - ENC[AES256_GCM,data:Z2/J2LkOvZLLu+nFcbZieb8=,iv:+VvdYrBX8ZpgKbRtbyD2DE7GaBOF7iDIb39rN8A8IeE=,tag:W1oiSOUffqjkZTQep6UNcA==,type:str]
    - ENC[AES256_GCM,data:qVZ8FbJLvwnQeTstnCcQ0deUP+/LiO6T6FA=,iv:3BWi8LW+/DhnbNX2dfqYYQlZLyqy5k4gPj88pevvohc=,tag:LWIfwwZDySbcntyCpBgGWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xjszg77q3ddquyvgh7scmwh27hk4ns0uef5w4y5feq2nnc0v8y4smgdan7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q09DYm94UkdHVkVMZjg5
            SkRQM2Z2ZllLYWljTlBGZXZtSVlGMGpqcldJCncvL3FQUFZMejRudDNzUlREL3A0
            TGQ3Mksrd3ZrL1pvZDEvaTdKMlNqMjAKLS0tIEZ1OENRclNYMHNRRGY0Unk5enRl
            MERTanpaNnlxcmI1b2w2eUp5TWJYSWcKlJdYwPxRBJXsY0d+/rBgDAXFC8pPBpyN
            +4vu+S54PTYFBNNyOClr5kVONfXQHQ0WWwTgcFV0Z2foR4ULuPC2AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T10:41:07Z"
    mac: ENC[AES256_GCM,data:U4RbNHlCOt2WwQqX9FvUyIcKEQPlzKUNNatNEhkw1Y2CUkbs75fedhjkJzoFrsvT0axJs5CasUZEQn3izHa4AnoV1pNbMCIANJefxYiANDVMzRfEjjPNW4ubgl3eAIa6erb7++2xBPBwVoFscnG0EsmJ7XBi3iwcjC65aam8QV4=,iv:9B+YmNUC/QirziVefGWUfQvqT6seZdaHVQn7uCAOWKc=,tag:/+QIDEMvpm2U+Nq+eZ6ZKA==,type:str]
    pgp: []
    encrypted_regex: ^(content|tls.crt|tls.key|crt|key|secret|secretboxEncryptionSecret|token|id|ca|data|environment)$
    version: 3.8.1
