createCustomResource: true
env:
  - name: ENABLE_NODEAGENT_CRD
    value: "1"
logging:
  enabled: true
  fluentd:
    disablePvc: true
    bufferStorageVolume:
      emptyDir:
        sizeLimit: 128Mi
  watchNamespaces: 
    - "*"
  clusterDomain: "talos.s3rv.dev."
  clusterFlows:
    - name: all
      spec:
        filters:
          - tag_normaliser:
              format: ${namespace_name}.${pod_name}.${container_name}
        match:
          - select: {}
        globalOutputRefs: ["loki"]
  clusterOutputs:
    - name: loki
      spec:
        loki:
          url: http://grafana-loki:3100
          configure_kubernetes_labels: true
          buffer:
            timekey: 1m
            timekey_wait: 30s
            timekey_use_utc: true