apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
  labels:
    notification: "true"
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: syncthing
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/la7eralus/k8s.git'
      path: apps/syncthing
      targetRevision: HEAD
  project: default