#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  pullPolicy: IfNotPresent
  tag: 2.7.2

env:
  TZ: Europe/Berlin
  PAPERLESS_TIME_ZONE: Europe/Berlin
  PAPERLESS_OCR_LANGUAGE: deu
  PAPERLESS_DATE_ORDER: "DMY"
  PAPERLESS_TASK_WORKERS: 2
  PAPERLESS_THREADS_PER_WORKER: 1
  PAPERLESS_WEBSERVER_WORKERS: 1
  PAPERLESS_FILENAME_FORMAT: "{created_year}/{document_type}/{correspondent}/{title}"
  PAPERLESS_URL: https://paperless.s3rv.dev
  PAPERLESS_REDIS: redis://redis

service:
  main:
    ports:
      http:
        port: 8000

persistence:
  data:
    enabled: true
    mountPath: /usr/src/paperless/data
    existingClaim: "paperless-ngx-data-pvc"
  media:
    enabled: true
    mountPath: /usr/src/paperless/media
    existingClaim: "paperless-ngx-media-pvc"
  export:
    enabled: false
  consume:
    enabled: false
  
redis:
  enabled: false